server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    username: 'tsvetanv'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/fraud
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true